// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVMZRlj9z07Ac3AgS-opmTeRHFKX3-vU',
    appId: '1:725888600273:web:85d27a475cae35a2779df0',
    messagingSenderId: '725888600273',
    projectId: 'student-complain-134c5',
    authDomain: 'student-complain-134c5.firebaseapp.com',
    storageBucket: 'student-complain-134c5.firebasestorage.app',
    measurementId: 'G-KN72XLS1DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQ1X80rBtdfi9xRS_UjQyh6JAfbiWC6M',
    appId: '1:725888600273:android:b5ff09015e747ce2779df0',
    messagingSenderId: '725888600273',
    projectId: 'student-complain-134c5',
    storageBucket: 'student-complain-134c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoY3LMVFqZkCA46WcBQ6uj7KzoOP2NKNc',
    appId: '1:725888600273:ios:5fa68cd89136a9ac779df0',
    messagingSenderId: '725888600273',
    projectId: 'student-complain-134c5',
    storageBucket: 'student-complain-134c5.firebasestorage.app',
    iosBundleId: 'com.example.studentComplaint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoY3LMVFqZkCA46WcBQ6uj7KzoOP2NKNc',
    appId: '1:725888600273:ios:5fa68cd89136a9ac779df0',
    messagingSenderId: '725888600273',
    projectId: 'student-complain-134c5',
    storageBucket: 'student-complain-134c5.firebasestorage.app',
    iosBundleId: 'com.example.studentComplaint1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqVMZRlj9z07Ac3AgS-opmTeRHFKX3-vU',
    appId: '1:725888600273:web:d436c1057e71c0a2779df0',
    messagingSenderId: '725888600273',
    projectId: 'student-complain-134c5',
    authDomain: 'student-complain-134c5.firebaseapp.com',
    storageBucket: 'student-complain-134c5.firebasestorage.app',
    measurementId: 'G-PNBD3WD2QM',
  );
}
